version: "3.8"

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_LOGLEVEL=debug

  textbelt:
    build: .
    container_name: textbelt-server
    ports:
      - "9090:9090"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: ["node", "server/app.js"]
